### ISSUE TITLE
OpenMod 3.0 Todo

### ISSUE THREAD

**Issue by Trojaner** [openmod/openmod#260]
- [x] openmod.commands.yaml getting reset
- [ ] openmod installer plugin for rocketmod
- [ ] openmod.users.yaml getting reset // fixed partially by throwing exception
- [ ] fix nuget optional resolving issues after openmod reload
- [ ] fix dispose issues (apparent random disposes & some disposes not getting called) 
- [ ] investigate random unloads 
- [ ] default implementation of economy provider which only throws exceptions and notifies user that an economy plugin is needed
- [ ] make hotloading configurable from openmod.yaml & make it enabled by default
- [ ] add packages.yaml
- [ ] change YamlDataStore to JsonDataStore (maybe add automatic migration too)
- [ ] /openmod update command, which also updates module; updates openmod without restart if using hotloading
(later: also autoupdate support for module)

**Comment by HanaForward** [comment]
Are there any friendly debugging options? such as dump Assembly load

**Comment by Charterino** [comment]
Cracking is not adviced and will not be helped with.

**Comment by HanaForward** [comment]
openmod decouples the project，So how do we debug the plugin?

**Comment by HanaForward** [comment]
Rockets are highly cohesive，Any plug-in only needs to maintain itself ，But openmod is low cohesion，The interaction between plug-ins needs to go through Ioc , Added minimum requirements for developers

**Comment by Trojaner** [comment]
Closing in favor of https://github.com/openmod/openmod/milestone/3
